import React, { createContext, useContext, useMemo, useState } from 'react';

const translations = {
  en: {
    appName: 'AutoParts IQ',
    iraqiPartsMarket: 'Iraqi spare parts marketplace',
    landingSubtitle: 'Find parts faster, receive supplier offers, and track orders from one place.',
    enterLogin: 'Enter / Log In',
    phoneLogin: 'Phone number login',
    enterPhone: 'Enter your phone number',
    phoneNumber: 'Phone number',
    continue: 'Continue',
    back: 'Back',
    enterOtp: 'Enter OTP',
    verifySignIn: 'Verify & Sign In',
    changeNumber: 'Change number',

    adminAccess: 'Admin Access',
    usernameEmailPhone: 'Username, email, or phone',
    password: 'Password',
    signIn: 'Sign in',
    signingIn: 'Signing in...',
    backToPhoneLogin: 'Back to phone login',

    roleCustomer: 'CUSTOMER',
    roleSupplier: 'SUPPLIER',
    roleAdmin: 'ADMIN',
    roleSuperAdmin: 'SUPER ADMIN',

    home: 'Home',
    orders: 'Orders',
    profile: 'Profile',
    leads: 'Leads',
    sentOffers: 'Sent Offers',
    earnings: 'Earnings',
    suppliers: 'Suppliers',
    dashboard: 'Dashboard',
    audit: 'Audit',
    users: 'Users',
    notifications: 'Notifications',
    close: 'Close',
    noNotifications: 'No notifications yet.',
    tapToOpen: 'Tap to open',

    hello: 'Hello',
    findParts: 'Find car parts faster',
    newRequest: '+ New Request',
    myRequests: 'My Requests',
    submitRequest: 'Submit Request',
    requestSubmitted: 'Your request was submitted successfully.',
    noMatchingRequests: 'No matching requests.',
    pending: 'Pending',
    cancelled: 'Cancelled',
    pendingCancelled: 'Pending + Cancelled',
    details: 'Details',
    hide: 'Hide',
    cancelRequest: 'Cancel request',
    reasonForCancellation: 'Reason for cancellation',
    confirmCancel: 'Confirm cancel',
    keepRequest: 'Keep request',
    requestCancelled: 'Request cancelled successfully.',

    selectOrigin: 'Select origin',
    selectMake: 'Select make',
    selectModel: 'Select model',
    selectYear: 'Select year',
    describeProblem: 'Describe problem e.g. squeaking brakes',
    aiIdentify: 'AI Identify Part',
    analyzing: 'Analyzing...',
    partName: 'Part name',
    partNumber: 'Part number',
    vinChassis: 'VIN / chassis',
    description: 'Description',
    requestPhotosUpTo4: 'Request photos — up to 4',
    uploadPhoto: 'Upload photo',
    uploading: 'Uploading...',
    imageHelp: 'JPG, PNG, WEBP, or GIF. Max 5MB per image.',
    yourPhone: 'Your phone',
    detailedLocation: 'Detailed location',

    supplier: 'Supplier',
    price: 'Price',
    condition: 'Condition',
    delivery: 'Delivery',
    new: 'New',
    used: 'Used',
    checkout: 'Checkout',
    offerAccepted: 'Offer accepted successfully. Your order has been created.',
    payment: 'Payment',
    paymentStatus: 'Payment status',
    driver: 'Driver',
    driverPhone: 'Driver phone',
    pickupEta: 'Pickup ETA',
    deliveryEta: 'Delivery ETA',
    deliveryComments: 'Delivery comments',
    notAssigned: 'Not assigned',

    supplierWorkspace: 'Supplier workspace',
    offersLeads: 'Offers & Leads',
    noMatchingLeads: 'No matching leads yet.',
    noMatchingSentOffers: 'No matching sent offers.',
    noAcceptedOrders: 'No accepted orders yet.',
    open: 'Open',
    addOfferItem: 'Add offer item',
    netPriceIqd: 'Net price IQD',
    notes: 'Notes',
    uploadOfferPhoto: 'Upload offer photo',
    addItem: 'Add Item',
    updateItem: 'Update Item',
    clear: 'Clear',
    itemsReady: 'Items ready to submit',
    submitOfferItems: 'Submit Offer Items',
    offerItemsSubmitted: 'Offer items submitted successfully.',
    edit: 'Edit',
    remove: 'Remove',
    cancelSentOffer: 'Cancel sent offer',
    confirmCancellation: 'Confirm cancellation',
    offerCancelled: 'Offer cancelled successfully.',
    yourPrice: 'Your price',
    completedEarningsOnly: 'Completed earnings only',
    completedOrders: 'Completed Orders',
    pendingOrders: 'Pending Orders',
    completedTransactions: 'Completed Transactions',
    noCompletedEarnings: 'No completed earnings transactions yet.',
    orderReadOnly: 'Order status is managed by Admin. Supplier view is read-only.',
    activeOrders: 'Active Orders',

    settings: 'Settings',
    language: 'Language',
    arabic: 'Arabic',
    english: 'English',
    mode: 'Mode',
    dark: 'Dark',
    light: 'Light',
    support: 'Support',
    logout: 'Log out',
    email: 'Email',
    phone: 'Phone',

    openImage: 'Open image',
    tapCloseToReturn: 'Tap Close to return',

    loading: 'Loading...',
    loadingCustomer: 'Loading customer workspace...',
    loadingSupplier: 'Loading supplier workspace...',
    validSupplierPrice: 'Valid supplier price is needed',
    addAtLeastOneItem: 'Add at least one item before submitting.',
    upload4: 'You can upload up to 4 request photos.',
    upload5: 'You can upload up to 5 offer photos.',
    rejected: 'Rejected',
    accepted: 'Accepted',
    allVisibleOffers: 'All visible offers'
  },

  ar: {
    appName: 'أوتو بارتس IQ',
    iraqiPartsMarket: 'سوق قطع الغيار العراقي',
    landingSubtitle: 'ابحث عن قطع الغيار بسرعة، استلم عروض الموردين، وتابع طلباتك من مكان واحد.',
    enterLogin: 'دخول',
    phoneLogin: 'تسجيل الدخول برقم الهاتف',
    enterPhone: 'أدخل رقم الهاتف',
    phoneNumber: 'رقم الهاتف',
    continue: 'متابعة',
    back: 'رجوع',
    enterOtp: 'أدخل رمز التحقق',
    verifySignIn: 'تحقق وتسجيل الدخول',
    changeNumber: 'تغيير الرقم',

    adminAccess: 'دخول الإدارة',
    usernameEmailPhone: 'اسم المستخدم أو البريد أو رقم الهاتف',
    password: 'كلمة المرور',
    signIn: 'تسجيل الدخول',
    signingIn: 'جارٍ تسجيل الدخول...',
    backToPhoneLogin: 'الرجوع لتسجيل الدخول بالهاتف',

    roleCustomer: 'عميل',
    roleSupplier: 'مورد',
    roleAdmin: 'مشرف',
    roleSuperAdmin: 'إدارة عليا',

    home: 'الرئيسية',
    orders: 'الطلبات',
    profile: 'الملف الشخصي',
    leads: 'الطلبات الجديدة',
    sentOffers: 'العروض المرسلة',
    earnings: 'الأرباح',
    suppliers: 'الموردون',
    dashboard: 'لوحة التحكم',
    audit: 'سجل العمليات',
    users: 'المستخدمون',
    notifications: 'الإشعارات',
    close: 'إغلاق',
    noNotifications: 'لا توجد إشعارات حالياً.',
    tapToOpen: 'اضغط للفتح',

    hello: 'مرحباً',
    findParts: 'اعثر على قطع غيار سيارتك بسرعة',
    newRequest: '+ طلب جديد',
    myRequests: 'طلباتي',
    submitRequest: 'إرسال الطلب',
    requestSubmitted: 'تم إرسال طلبك بنجاح.',
    noMatchingRequests: 'لا توجد طلبات مطابقة.',
    pending: 'قيد الانتظار',
    cancelled: 'ملغي',
    pendingCancelled: 'قيد الانتظار + ملغي',
    details: 'التفاصيل',
    hide: 'إخفاء',
    cancelRequest: 'إلغاء الطلب',
    reasonForCancellation: 'سبب الإلغاء',
    confirmCancel: 'تأكيد الإلغاء',
    keepRequest: 'الإبقاء على الطلب',
    requestCancelled: 'تم إلغاء الطلب بنجاح.',

    selectOrigin: 'اختر المنشأ',
    selectMake: 'اختر الشركة المصنعة',
    selectModel: 'اختر الموديل',
    selectYear: 'اختر السنة',
    describeProblem: 'صف المشكلة، مثال: صوت في الفرامل',
    aiIdentify: 'تحديد القطعة بالذكاء الاصطناعي',
    analyzing: 'جارٍ التحليل...',
    partName: 'اسم القطعة',
    partNumber: 'رقم القطعة',
    vinChassis: 'رقم الشاصي / VIN',
    description: 'الوصف',
    requestPhotosUpTo4: 'صور الطلب — حتى 4 صور',
    uploadPhoto: 'رفع صورة',
    uploading: 'جارٍ الرفع...',
    imageHelp: 'الصيغ المسموحة JPG أو PNG أو WEBP أو GIF. الحد الأقصى 5MB للصورة.',
    yourPhone: 'رقم هاتفك',
    detailedLocation: 'الموقع التفصيلي',

    supplier: 'المورد',
    price: 'السعر',
    condition: 'الحالة',
    delivery: 'التوصيل',
    new: 'جديد',
    used: 'مستعمل',
    checkout: 'تأكيد الطلب',
    offerAccepted: 'تم قبول العرض بنجاح وتم إنشاء الطلب.',
    payment: 'طريقة الدفع',
    paymentStatus: 'حالة الدفع',
    driver: 'السائق',
    driverPhone: 'هاتف السائق',
    pickupEta: 'موعد الاستلام المتوقع',
    deliveryEta: 'موعد التوصيل المتوقع',
    deliveryComments: 'ملاحظات التوصيل',
    notAssigned: 'لم يتم التعيين',

    supplierWorkspace: 'مساحة المورد',
    offersLeads: 'العروض والطلبات الجديدة',
    noMatchingLeads: 'لا توجد طلبات جديدة مطابقة حالياً.',
    noMatchingSentOffers: 'لا توجد عروض مرسلة مطابقة.',
    noAcceptedOrders: 'لا توجد طلبات مقبولة حالياً.',
    open: 'فتح',
    addOfferItem: 'إضافة عرض',
    netPriceIqd: 'السعر الصافي بالدينار',
    notes: 'ملاحظات',
    uploadOfferPhoto: 'رفع صورة العرض',
    addItem: 'إضافة',
    updateItem: 'تحديث',
    clear: 'مسح',
    itemsReady: 'عروض جاهزة للإرسال',
    submitOfferItems: 'إرسال العروض',
    offerItemsSubmitted: 'تم إرسال العروض بنجاح.',
    edit: 'تعديل',
    remove: 'حذف',
    cancelSentOffer: 'إلغاء العرض المرسل',
    confirmCancellation: 'تأكيد الإلغاء',
    offerCancelled: 'تم إلغاء العرض بنجاح.',
    yourPrice: 'سعرك',
    completedEarningsOnly: 'الأرباح من الطلبات المكتملة فقط',
    completedOrders: 'الطلبات المكتملة',
    pendingOrders: 'الطلبات قيد التنفيذ',
    completedTransactions: 'العمليات المكتملة',
    noCompletedEarnings: 'لا توجد أرباح مكتملة حالياً.',
    orderReadOnly: 'حالة الطلب تُدار من قبل الإدارة. عرض المورد للقراءة فقط.',
    activeOrders: 'الطلبات النشطة',

    settings: 'الإعدادات',
    language: 'اللغة',
    arabic: 'العربية',
    english: 'الإنجليزية',
    mode: 'الوضع',
    dark: 'داكن',
    light: 'فاتح',
    support: 'الدعم',
    logout: 'تسجيل الخروج',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',

    openImage: 'فتح الصورة',
    tapCloseToReturn: 'اضغط إغلاق للعودة',

    loading: 'جارٍ التحميل...',
    loadingCustomer: 'جارٍ تحميل مساحة العميل...',
    loadingSupplier: 'جارٍ تحميل مساحة المورد...',
    validSupplierPrice: 'أدخل سعراً صحيحاً من المورد',
    addAtLeastOneItem: 'أضف عرضاً واحداً على الأقل قبل الإرسال.',
    upload4: 'يمكنك رفع حتى 4 صور للطلب.',
    upload5: 'يمكنك رفع حتى 5 صور للعرض.',
    rejected: 'مرفوض',
    accepted: 'مقبول',
    allVisibleOffers: 'كل العروض الظاهرة'
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(localStorage.getItem('language') || 'en');
  const value = useMemo(() => ({
    language,
    direction: language === 'ar' ? 'rtl' : 'ltr',
    t: key => translations[language][key] || translations.en[key] || key,
    toggleLanguage: () => {
      const next = language === 'en' ? 'ar' : 'en';
      localStorage.setItem('language', next);
      setLanguage(next);
    }
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export const useLanguage = () => useContext(LanguageContext);
