import React, { createContext, useContext, useMemo, useState } from 'react';

const translations = {
  en: {
    appName: 'AutoParts IQ',
    iraqiPartsMarket: 'Iraqi spare parts marketplace',
    landingSubtitle: 'Find parts faster, receive supplier offers, and track orders from one place.',
    enterLogin: 'Enter / Log In',
    phoneLogin: 'Phone number login',
    enterPhone: 'Enter your phone number',
    phoneNumber: 'Phone number',
    continue: 'Continue',
    back: 'Back',
    enterOtp: 'Enter OTP',
    otpRequired: 'Please enter the verification code.',
    incorrectOtp: 'Incorrect OTP. Please try again.',
    verifySignIn: 'Verify & Sign In',
    changeNumber: 'Change number',

    adminAccess: 'Admin Access',
    usernameEmailPhone: 'Username, email, or phone',
    password: 'Password',
    signIn: 'Sign in',
    signingIn: 'Signing in...',
    backToPhoneLogin: 'Back to phone login',

    roleCustomer: 'CUSTOMER',
    roleSupplier: 'SUPPLIER',
    roleAdmin: 'ADMIN',
    roleSuperAdmin: 'SUPER ADMIN',

    home: 'Home',
    orders: 'Orders',
    profile: 'Profile',
    leads: 'Leads',
    sentOffers: 'Sent Offers',
    activeOffers: 'Active Offers',
    requestDetails: 'Request Details',
    offerDetails: 'Offer Details',
    earnings: 'Earnings',
    suppliers: 'Suppliers',
    dashboard: 'Dashboard',
    audit: 'Audit',
    users: 'Users',
    notifications: 'Notifications',
    close: 'Close',
    noNotifications: 'No notifications yet.',
    tapToOpen: 'Tap to open',

    hello: 'Hello',
    findParts: 'Find car parts faster',
    newRequest: '+ New Request',
    myRequests: 'My Requests',
    openRequests: 'Open Requests',
    submitRequest: 'Submit Request',
    requestSubmitted: 'Your request was submitted successfully.',
    noMatchingRequests: 'No matching requests.',
    pending: 'Pending',
    cancelled: 'Cancelled',
    pendingCancelled: 'Pending + Cancelled',
    details: 'Details',
    partDetails: 'Part / Request',
    hide: 'Hide',
    cancelRequest: 'Cancel request',
    reasonForCancellation: 'Reason for cancellation',
    confirmCancel: 'Confirm cancel',
    keepRequest: 'Keep request',
    requestCancelled: 'Request cancelled successfully.',

    selectOrigin: 'Select origin',
    selectMake: 'Select make',
    selectModel: 'Select model',
    selectYear: 'Select year',
    describeProblem: 'Describe problem e.g. squeaking brakes',
    aiIdentify: 'AI Identify Part',
    analyzing: 'Analyzing...',
    partName: 'Part name',
    partNumber: 'Part number',
    vinChassis: 'VIN / chassis',
    description: 'Description',
    requestPhotosUpTo4: 'Request photos â€” up to 4',
    uploadPhoto: 'Upload photo',
    uploading: 'Uploading...',
    imageHelp: 'JPG, PNG, WEBP, or GIF. Max 5MB per image.',
    yourPhone: 'Your phone',
    detailedLocation: 'Detailed location',

    supplier: 'Supplier',
    price: 'Price',
    priceBreakdown: 'Price Breakdown',
    condition: 'Condition',
    delivery: 'Delivery',
    new: 'New',
    used: 'Used',
    checkout: 'Checkout',
    offerAccepted: 'Offer accepted successfully. Your order has been created.',
    payment: 'Payment',
    paymentStatus: 'Payment status',
    driver: 'Driver',
    driverPhone: 'Driver phone',
    pickupEta: 'Pickup ETA',
    deliveryEta: 'Delivery ETA',
    deliveryComments: 'Delivery comments',
    notAssigned: 'Not assigned',

    supplierWorkspace: 'Supplier workspace',
    offersLeads: 'Offers & Leads',
    noMatchingLeads: 'No matching leads yet.',
    noMatchingSentOffers: 'No matching sent offers.',
    noAcceptedOrders: 'No accepted orders yet.',
    open: 'Open',
    addOfferItem: 'Add offer item',
    netPriceIqd: 'Net price IQD',
    notes: 'Notes',
    uploadOfferPhoto: 'Upload offer photo',
    addItem: 'Add Item',
    updateItem: 'Update Item',
    clear: 'Clear',
    itemsReady: 'Items ready to submit',
    submitOfferItems: 'Submit Offer Items',
    offerItemsSubmitted: 'Offer items submitted successfully.',
    edit: 'Edit',
    remove: 'Remove',
    cancelSentOffer: 'Cancel sent offer',
    confirmCancellation: 'Confirm cancellation',
    offerCancelled: 'Offer cancelled successfully.',
    yourPrice: 'Your price',
    completedEarningsOnly: 'Completed earnings only',
    pendingValue: 'Pending Value',
    pendingValueNote: 'Pending value is not final until the order is completed.',
    openOrders: 'Open Orders',
    openTransactions: 'Open Transactions',
    noPendingValue: 'No pending value transactions.',
    completedOrders: 'Completed Orders',
    pendingOrders: 'Pending Orders',
    completedTransactions: 'Completed Transactions',
    noCompletedEarnings: 'No completed earnings transactions yet.',
    orderReadOnly: 'Order status is managed by Admin. Supplier view is read-only.',
    activeOrders: 'Open Orders',

    settings: 'Settings',
    language: 'Language',
    arabic: 'Arabic',
    english: 'English',
    mode: 'Mode',
    dark: 'Dark',
    light: 'Light',
    support: 'Support',
    supportWhatsapp: 'Support / WhatsApp',
    supportEmail: 'Support Email',
    logout: 'Log out',
    email: 'Email',
    phone: 'Phone',

    openImage: 'Open image',
    tapCloseToReturn: 'Tap Close to return',

    loading: 'Loading...',
    loadingCustomer: 'Loading customer workspace...',
    loadingSupplier: 'Loading supplier workspace...',
    validSupplierPrice: 'Valid supplier price is needed',
    addAtLeastOneItem: 'Add at least one item before submitting.',
    upload4: 'You can upload up to 4 request photos.',
    upload5: 'You can upload up to 5 offer photos.',
    rejected: 'Rejected',
    accepted: 'Accepted',
    allVisibleOffers: 'All visible offers',
    waitingPickup: 'Waiting pickup',
    delivering: 'Delivering',
    completed: 'Completed',
    deliveryCancelled: 'Delivery cancelled. Admin or support should review this order.',
    deliveryWorkflow: 'Delivery workflow',
    deliveryWorkflowNote: 'Driver assignment, pickup time, delivery ETA, and proof of delivery are managed by Admin.',
    adminDashboard: 'AutoPartIQ Admin',
    platformOverview: 'Platform overview',
    loadingDashboard: 'Loading dashboard...',
    ordersOnlyAdminAccess: 'Orders-only admin access.',
    superAdminOnlyUsers: 'Only Super Admin can manage admin users.',
    adminUsers: 'Admin Users',
    auditLogs: 'Audit Logs',
    supplierName: 'Supplier name',
    editSupplier: 'Edit Supplier',
    editSupplierHint: 'Update supplier details, supported origins, and active status.',
    supplierDetails: 'Supplier Details',
    supportedMakes: 'Supported Makes',
    supportedMakesHint: 'Choose the origins this supplier can serve.',
    supplierWillReceiveLeads: 'Supplier will receive matching leads.',
    supplierWillNotReceiveLeads: 'Supplier will not receive new leads.',
    location: 'Location',
    addSupplier: 'Add Supplier',
    addSupplierHint: 'Create a supplier profile and choose supported origins.',
    allOrders: 'All Orders',
    searchOrderPartSupplier: 'Search order, part, or supplier',
    allStatuses: 'All statuses',
    from: 'From',
    to: 'To',
    clearFilters: 'Clear filters',
    showing: 'Showing',
    of: 'of',
    noMatchingOrders: 'No matching orders.',
    customerPhone: 'Customer phone',
    customer: 'Customer',
    revenue: 'Revenue',
    status: 'Status',
    cancel: 'Cancel',
    requests: 'Requests',
    platformRevenue: 'Platform Revenue',
    pendingPayments: 'Pending Payments',
    paidOrders: 'Paid Orders',
    activeSuppliers: 'Active Suppliers',
    supplierEarnings: 'Supplier Earnings',
    noSuppliersYet: 'No suppliers yet.',
    active: 'Active',
    disabled: 'Disabled',
    makes: 'Makes',
    none: 'None',
    disable: 'Disable',
    activeSupplier: 'Active supplier',
    save: 'Save',
    saving: 'Saving...',
    loadingAuditLogs: 'Loading audit logs...',
    noAuditLogsYet: 'No audit logs yet.',
    by: 'By',
    system: 'System',
    paymentControls: 'Payment controls',
    cashOnDelivery: 'Cash on delivery',
    card: 'Card',
    wallet: 'Wallet',
    bankTransfer: 'Bank transfer',
    paid: 'Paid',
    failed: 'Failed',
    refunded: 'Refunded',
    updatePayment: 'Update payment',
    deliveryAssignment: 'Delivery assignment',
    driverName: 'Driver name',
    proofOfDeliveryUrl: 'Proof of delivery URL',
    proofOfDeliveryImage: 'Proof of delivery image',
    viewProofOfDelivery: 'View proof of delivery',
    deliveryNotes: 'Delivery notes / customer comments',
    updateDelivery: 'Update delivery',
    createAdminUser: 'Create Admin User',
    superAdminCreated: 'Super Admin created successfully.',
    adminCreated: 'Admin created successfully.',
    fullAdminDescription: 'Full Admin: dashboard, suppliers, orders, audit',
    ordersOnlyDescription: 'Orders Only: order management only',
    fullName: 'Full name',
    phoneNumberForLogin: 'Phone number used for login',
    adminPhoneLoginNote: 'Admin and Super Admin users can log in from the main phone login screen using their registered phone number. The corner SA button remains available for emergency username/access-code access only.',
    createUser: 'Create User',
    checkoutPreview: 'Checkout preview',
    confirmOrder: 'Confirm order',
    itemPrice: 'Item price',
    deliveryFee: 'Delivery fee',
    total: 'Total',
    paymentPlaceholder: 'Cash on delivery is active for MVP. Card and wallet payment can be connected later.',
    confirming: 'Confirming...',
    notAvailable: 'N/A',
    origin: 'Origin',
    make: 'Make',
    model: 'Model',
    year: 'Year',
    activeOffer: 'Active',
    waiting: 'Waiting',
    processing: 'Processing',
    newOfferNotification: 'You have a new offer',
    offerAcceptedNotification: 'Your offer was accepted',
    orderStatusUpdatedNotification: 'Order status updated',
    orderPaymentUpdatedNotification: 'Payment updated',
    orderDeliveryUpdatedNotification: 'Delivery details updated',
    proofOfDeliveryUpdatedNotification: 'Proof of delivery updated',
    created: 'Created',
    noOrders: 'No orders yet.',
    user: 'User',
    order: 'Order',
    auditAdminUserCreated: 'Admin user created',
    auditOrderStatusUpdated: 'Order status updated',
    auditSupplierCreated: 'Supplier created',
    auditSupplierUpdated: 'Supplier updated',
    auditSupplierDisabled: 'Supplier disabled',
    auditPaymentUpdated: 'Payment updated',
    auditDeliveryUpdated: 'Delivery updated'
  },

  ar: {
    appName: 'Ø£ÙˆØªÙˆ Ø¨Ø§Ø±ØªØ³ IQ',
    iraqiPartsMarket: 'Ø³ÙˆÙ‚ Ù‚Ø·Ø¹ Ø§Ù„ØºÙŠØ§Ø± Ø§Ù„Ø¹Ø±Ø§Ù‚ÙŠ',
    landingSubtitle: 'Ø§Ø¨Ø­Ø« Ø¹Ù† Ù‚Ø·Ø¹ Ø§Ù„ØºÙŠØ§Ø± Ø¨Ø³Ø±Ø¹Ø©ØŒ Ø§Ø³ØªÙ„Ù… Ø¹Ø±ÙˆØ¶ Ø§Ù„Ù…ÙˆØ±Ø¯ÙŠÙ†ØŒ ÙˆØªØ§Ø¨Ø¹ Ø·Ù„Ø¨Ø§ØªÙƒ Ù…Ù† Ù…ÙƒØ§Ù† ÙˆØ§Ø­Ø¯.',
    enterLogin: 'Ø¯Ø®ÙˆÙ„',
    phoneLogin: 'ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„ Ø¨Ø±Ù‚Ù… Ø§Ù„Ù‡Ø§ØªÙ',
    enterPhone: 'Ø£Ø¯Ø®Ù„ Ø±Ù‚Ù… Ø§Ù„Ù‡Ø§ØªÙ',
    phoneNumber: 'Ø±Ù‚Ù… Ø§Ù„Ù‡Ø§ØªÙ',
    continue: 'Ù…ØªØ§Ø¨Ø¹Ø©',
    back: 'Ø±Ø¬ÙˆØ¹',
    enterOtp: 'Ø£Ø¯Ø®Ù„ Ø±Ù…Ø² Ø§Ù„ØªØ­Ù‚Ù‚',
    verifySignIn: 'ØªØ­Ù‚Ù‚ ÙˆØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„',
    changeNumber: 'ØªØºÙŠÙŠØ± Ø§Ù„Ø±Ù‚Ù…',

    adminAccess: 'Ø¯Ø®ÙˆÙ„ Ø§Ù„Ø¥Ø¯Ø§Ø±Ø©',
    usernameEmailPhone: 'Ø§Ø³Ù… Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù… Ø£Ùˆ Ø§Ù„Ø¨Ø±ÙŠØ¯ Ø£Ùˆ Ø±Ù‚Ù… Ø§Ù„Ù‡Ø§ØªÙ',
    password: 'ÙƒÙ„Ù…Ø© Ø§Ù„Ù…Ø±ÙˆØ±',
    signIn: 'ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„',
    signingIn: 'Ø¬Ø§Ø±Ù ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„...',
    backToPhoneLogin: 'Ø§Ù„Ø±Ø¬ÙˆØ¹ Ù„ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„ Ø¨Ø§Ù„Ù‡Ø§ØªÙ',

    roleCustomer: 'Ø¹Ù…ÙŠÙ„',
    roleSupplier: 'Ù…ÙˆØ±Ø¯',
    roleAdmin: 'Ù…Ø´Ø±Ù',
    roleSuperAdmin: 'Ø¥Ø¯Ø§Ø±Ø© Ø¹Ù„ÙŠØ§',

    home: 'Ø§Ù„Ø±Ø¦ÙŠØ³ÙŠØ©',
    orders: 'Ø§Ù„Ø·Ù„Ø¨Ø§Øª',
    profile: 'Ø§Ù„Ù…Ù„Ù Ø§Ù„Ø´Ø®ØµÙŠ',
    leads: 'Ø§Ù„Ø·Ù„Ø¨Ø§Øª Ø§Ù„Ø¬Ø¯ÙŠØ¯Ø©',
    sentOffers: 'Ø§Ù„Ø¹Ø±ÙˆØ¶ Ø§Ù„Ù…Ø±Ø³Ù„Ø©',
    activeOffers: 'Ø§Ù„Ø¹Ø±ÙˆØ¶ Ø§Ù„Ù†Ø´Ø·Ø©',
    requestDetails: 'ØªÙØ§ØµÙŠÙ„ Ø§Ù„Ø·Ù„Ø¨',
    offerDetails: 'ØªÙØ§ØµÙŠÙ„ Ø§Ù„Ø¹Ø±Ø¶',
    earnings: 'Ø§Ù„Ø£Ø±Ø¨Ø§Ø­',
    suppliers: 'Ø§Ù„Ù…ÙˆØ±Ø¯ÙˆÙ†',
    dashboard: 'Ù„ÙˆØ­Ø© Ø§Ù„ØªØ­ÙƒÙ…',
    audit: 'Ø³Ø¬Ù„ Ø§Ù„Ø¹Ù…Ù„ÙŠØ§Øª',
    users: 'Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù…ÙˆÙ†',
    notifications: 'Ø§Ù„Ø¥Ø´Ø¹Ø§Ø±Ø§Øª',
    close: 'Ø¥ØºÙ„Ø§Ù‚',
    noNotifications: 'Ù„Ø§ ØªÙˆØ¬Ø¯ Ø¥Ø´Ø¹Ø§Ø±Ø§Øª Ø­Ø§Ù„ÙŠØ§Ù‹.',
    tapToOpen: 'Ø§Ø¶ØºØ· Ù„Ù„ÙØªØ­',

    hello: 'Ù…Ø±Ø­Ø¨Ø§Ù‹',
    findParts: 'Ø§Ø¹Ø«Ø± Ø¹Ù„Ù‰ Ù‚Ø·Ø¹ ØºÙŠØ§Ø± Ø³ÙŠØ§Ø±ØªÙƒ Ø¨Ø³Ø±Ø¹Ø©',
    newRequest: '+ Ø·Ù„Ø¨ Ø¬Ø¯ÙŠØ¯',
    myRequests: 'Ø·Ù„Ø¨Ø§ØªÙŠ',
    openRequests: 'Ø§Ù„Ø·Ù„Ø¨Ø§Øª Ø§Ù„Ù…ÙØªÙˆØ­Ø©',
    submitRequest: 'Ø¥Ø±Ø³Ø§Ù„ Ø§Ù„Ø·Ù„Ø¨',
    requestSubmitted: 'ØªÙ… Ø¥Ø±Ø³Ø§Ù„ Ø·Ù„Ø¨Ùƒ Ø¨Ù†Ø¬Ø§Ø­.',
    noMatchingRequests: 'Ù„Ø§ ØªÙˆØ¬Ø¯ Ø·Ù„Ø¨Ø§Øª Ù…Ø·Ø§Ø¨Ù‚Ø©.',
    pending: 'Ù‚ÙŠØ¯ Ø§Ù„Ø§Ù†ØªØ¸Ø§Ø±',
    cancelled: 'Ù…Ù„ØºÙŠ',
    pendingCancelled: 'Ù‚ÙŠØ¯ Ø§Ù„Ø§Ù†ØªØ¸Ø§Ø± + Ù…Ù„ØºÙŠ',
    details: 'Ø§Ù„ØªÙØ§ØµÙŠÙ„',
    partDetails: 'ØªÙØ§ØµÙŠÙ„ Ø§Ù„Ù‚Ø·Ø¹Ø© / Ø§Ù„Ø·Ù„Ø¨',
    hide: 'Ø¥Ø®ÙØ§Ø¡',
    cancelRequest: 'Ø¥Ù„ØºØ§Ø¡ Ø§Ù„Ø·Ù„Ø¨',
    reasonForCancellation: 'Ø³Ø¨Ø¨ Ø§Ù„Ø¥Ù„ØºØ§Ø¡',
    confirmCancel: 'ØªØ£ÙƒÙŠØ¯ Ø§Ù„Ø¥Ù„ØºØ§Ø¡',
    keepRequest: 'Ø§Ù„Ø¥Ø¨Ù‚Ø§Ø¡ Ø¹Ù„Ù‰ Ø§Ù„Ø·Ù„Ø¨',
    requestCancelled: 'ØªÙ… Ø¥Ù„ØºØ§Ø¡ Ø§Ù„Ø·Ù„Ø¨ Ø¨Ù†Ø¬Ø§Ø­.',

    selectOrigin: 'Ø§Ø®ØªØ± Ø§Ù„Ù…Ù†Ø´Ø£',
    selectMake: 'Ø§Ø®ØªØ± Ø§Ù„Ø´Ø±ÙƒØ© Ø§Ù„Ù…ØµÙ†Ø¹Ø©',
    selectModel: 'Ø§Ø®ØªØ± Ø§Ù„Ù…ÙˆØ¯ÙŠÙ„',
    selectYear: 'Ø§Ø®ØªØ± Ø§Ù„Ø³Ù†Ø©',
    describeProblem: 'ØµÙ Ø§Ù„Ù…Ø´ÙƒÙ„Ø©ØŒ Ù…Ø«Ø§Ù„: ØµÙˆØª ÙÙŠ Ø§Ù„ÙØ±Ø§Ù…Ù„',
    aiIdentify: 'ØªØ­Ø¯ÙŠØ¯ Ø§Ù„Ù‚Ø·Ø¹Ø© Ø¨Ø§Ù„Ø°ÙƒØ§Ø¡ Ø§Ù„Ø§ØµØ·Ù†Ø§Ø¹ÙŠ',
    analyzing: 'Ø¬Ø§Ø±Ù Ø§Ù„ØªØ­Ù„ÙŠÙ„...',
    partName: 'Ø§Ø³Ù… Ø§Ù„Ù‚Ø·Ø¹Ø©',
    partNumber: 'Ø±Ù‚Ù… Ø§Ù„Ù‚Ø·Ø¹Ø©',
    vinChassis: 'Ø±Ù‚Ù… Ø§Ù„Ø´Ø§ØµÙŠ / VIN',
    description: 'Ø§Ù„ÙˆØµÙ',
    requestPhotosUpTo4: 'ØµÙˆØ± Ø§Ù„Ø·Ù„Ø¨ â€” Ø­ØªÙ‰ 4 ØµÙˆØ±',
    uploadPhoto: 'Ø±ÙØ¹ ØµÙˆØ±Ø©',
    uploading: 'Ø¬Ø§Ø±Ù Ø§Ù„Ø±ÙØ¹...',
    imageHelp: 'Ø§Ù„ØµÙŠØº Ø§Ù„Ù…Ø³Ù…ÙˆØ­Ø© JPG Ø£Ùˆ PNG Ø£Ùˆ WEBP Ø£Ùˆ GIF. Ø§Ù„Ø­Ø¯ Ø§Ù„Ø£Ù‚ØµÙ‰ 5MB Ù„Ù„ØµÙˆØ±Ø©.',
    yourPhone: 'Ø±Ù‚Ù… Ù‡Ø§ØªÙÙƒ',
    detailedLocation: 'Ø§Ù„Ù…ÙˆÙ‚Ø¹ Ø§Ù„ØªÙØµÙŠÙ„ÙŠ',

    supplier: 'Ø§Ù„Ù…ÙˆØ±Ø¯',
    price: 'Ø§Ù„Ø³Ø¹Ø±',
    priceBreakdown: 'ØªÙØ§ØµÙŠÙ„ Ø§Ù„Ø³Ø¹Ø±',
    condition: 'Ø§Ù„Ø­Ø§Ù„Ø©',
    delivery: 'Ø§Ù„ØªÙˆØµÙŠÙ„',
    new: 'Ø¬Ø¯ÙŠØ¯',
    used: 'Ù…Ø³ØªØ¹Ù…Ù„',
    checkout: 'ØªØ£ÙƒÙŠØ¯ Ø§Ù„Ø·Ù„Ø¨',
    offerAccepted: 'ØªÙ… Ù‚Ø¨ÙˆÙ„ Ø§Ù„Ø¹Ø±Ø¶ Ø¨Ù†Ø¬Ø§Ø­ ÙˆØªÙ… Ø¥Ù†Ø´Ø§Ø¡ Ø§Ù„Ø·Ù„Ø¨.',
    payment: 'Ø·Ø±ÙŠÙ‚Ø© Ø§Ù„Ø¯ÙØ¹',
    paymentStatus: 'Ø­Ø§Ù„Ø© Ø§Ù„Ø¯ÙØ¹',
    driver: 'Ø§Ù„Ø³Ø§Ø¦Ù‚',
    driverPhone: 'Ù‡Ø§ØªÙ Ø§Ù„Ø³Ø§Ø¦Ù‚',
    pickupEta: 'Ù…ÙˆØ¹Ø¯ Ø§Ù„Ø§Ø³ØªÙ„Ø§Ù… Ø§Ù„Ù…ØªÙˆÙ‚Ø¹',
    deliveryEta: 'Ù…ÙˆØ¹Ø¯ Ø§Ù„ØªÙˆØµÙŠÙ„ Ø§Ù„Ù…ØªÙˆÙ‚Ø¹',
    deliveryComments: 'Ù…Ù„Ø§Ø­Ø¸Ø§Øª Ø§Ù„ØªÙˆØµÙŠÙ„',
    notAssigned: 'Ù„Ù… ÙŠØªÙ… Ø§Ù„ØªØ¹ÙŠÙŠÙ†',

    supplierWorkspace: 'Ù…Ø³Ø§Ø­Ø© Ø§Ù„Ù…ÙˆØ±Ø¯',
    offersLeads: 'Ø§Ù„Ø¹Ø±ÙˆØ¶ ÙˆØ§Ù„Ø·Ù„Ø¨Ø§Øª Ø§Ù„Ø¬Ø¯ÙŠØ¯Ø©',
    noMatchingLeads: 'Ù„Ø§ ØªÙˆØ¬Ø¯ Ø·Ù„Ø¨Ø§Øª Ø¬Ø¯ÙŠØ¯Ø© Ù…Ø·Ø§Ø¨Ù‚Ø© Ø­Ø§Ù„ÙŠØ§Ù‹.',
    noMatchingSentOffers: 'Ù„Ø§ ØªÙˆØ¬Ø¯ Ø¹Ø±ÙˆØ¶ Ù…Ø±Ø³Ù„Ø© Ù…Ø·Ø§Ø¨Ù‚Ø©.',
    noAcceptedOrders: 'Ù„Ø§ ØªÙˆØ¬Ø¯ Ø·Ù„Ø¨Ø§Øª Ù…Ù‚Ø¨ÙˆÙ„Ø© Ø­Ø§Ù„ÙŠØ§Ù‹.',
    open: 'ÙØªØ­',
    addOfferItem: 'Ø¥Ø¶Ø§ÙØ© Ø¹Ø±Ø¶',
    netPriceIqd: 'Ø§Ù„Ø³Ø¹Ø± Ø§Ù„ØµØ§ÙÙŠ Ø¨Ø§Ù„Ø¯ÙŠÙ†Ø§Ø±',
    notes: 'Ù…Ù„Ø§Ø­Ø¸Ø§Øª',
    uploadOfferPhoto: 'Ø±ÙØ¹ ØµÙˆØ±Ø© Ø§Ù„Ø¹Ø±Ø¶',
    addItem: 'Ø¥Ø¶Ø§ÙØ©',
    updateItem: 'ØªØ­Ø¯ÙŠØ«',
    clear: 'Ù…Ø³Ø­',
    itemsReady: 'Ø¹Ø±ÙˆØ¶ Ø¬Ø§Ù‡Ø²Ø© Ù„Ù„Ø¥Ø±Ø³Ø§Ù„',
    submitOfferItems: 'Ø¥Ø±Ø³Ø§Ù„ Ø§Ù„Ø¹Ø±ÙˆØ¶',
    offerItemsSubmitted: 'ØªÙ… Ø¥Ø±Ø³Ø§Ù„ Ø§Ù„Ø¹Ø±ÙˆØ¶ Ø¨Ù†Ø¬Ø§Ø­.',
    edit: 'ØªØ¹Ø¯ÙŠÙ„',
    remove: 'Ø­Ø°Ù',
    cancelSentOffer: 'Ø¥Ù„ØºØ§Ø¡ Ø§Ù„Ø¹Ø±Ø¶ Ø§Ù„Ù…Ø±Ø³Ù„',
    confirmCancellation: 'ØªØ£ÙƒÙŠØ¯ Ø§Ù„Ø¥Ù„ØºØ§Ø¡',
    offerCancelled: 'ØªÙ… Ø¥Ù„ØºØ§Ø¡ Ø§Ù„Ø¹Ø±Ø¶ Ø¨Ù†Ø¬Ø§Ø­.',
    yourPrice: 'Ø³Ø¹Ø±Ùƒ',
    completedEarningsOnly: 'Ø§Ù„Ø£Ø±Ø¨Ø§Ø­ Ù…Ù† Ø§Ù„Ø·Ù„Ø¨Ø§Øª Ø§Ù„Ù…ÙƒØªÙ…Ù„Ø© ÙÙ‚Ø·',
    pendingValue: 'Ø§Ù„Ù‚ÙŠÙ…Ø© Ø§Ù„Ù…Ø¹Ù„Ù‚Ø©',
    pendingValueNote: 'Ø§Ù„Ù‚ÙŠÙ…Ø© Ø§Ù„Ù…Ø¹Ù„Ù‚Ø© Ù„ÙŠØ³Øª Ù†Ù‡Ø§Ø¦ÙŠØ© Ø­ØªÙ‰ Ø§ÙƒØªÙ…Ø§Ù„ Ø§Ù„Ø·Ù„Ø¨.',
    openOrders: 'Ø§Ù„Ø·Ù„Ø¨Ø§Øª Ø§Ù„Ù…ÙØªÙˆØ­Ø©',
    openTransactions: 'Ø§Ù„Ø¹Ù…Ù„ÙŠØ§Øª Ø§Ù„Ù…ÙØªÙˆØ­Ø©',
    noPendingValue: 'Ù„Ø§ ØªÙˆØ¬Ø¯ Ù‚ÙŠÙ… Ù…Ø¹Ù„Ù‚Ø© Ø­Ø§Ù„ÙŠØ§Ù‹.',
    completedOrders: 'Ø§Ù„Ø·Ù„Ø¨Ø§Øª Ø§Ù„Ù…ÙƒØªÙ…Ù„Ø©',
    pendingOrders: 'Ø§Ù„Ø·Ù„Ø¨Ø§Øª Ù‚ÙŠØ¯ Ø§Ù„ØªÙ†ÙÙŠØ°',
    completedTransactions: 'Ø§Ù„Ø¹Ù…Ù„ÙŠØ§Øª Ø§Ù„Ù…ÙƒØªÙ…Ù„Ø©',
    noCompletedEarnings: 'Ù„Ø§ ØªÙˆØ¬Ø¯ Ø£Ø±Ø¨Ø§Ø­ Ù…ÙƒØªÙ…Ù„Ø© Ø­Ø§Ù„ÙŠØ§Ù‹.',
    orderReadOnly: 'Ø­Ø§Ù„Ø© Ø§Ù„Ø·Ù„Ø¨ ØªÙØ¯Ø§Ø± Ù…Ù† Ù‚Ø¨Ù„ Ø§Ù„Ø¥Ø¯Ø§Ø±Ø©. Ø¹Ø±Ø¶ Ø§Ù„Ù…ÙˆØ±Ø¯ Ù„Ù„Ù‚Ø±Ø§Ø¡Ø© ÙÙ‚Ø·.',
    activeOrders: 'Ø§Ù„Ø·Ù„Ø¨Ø§Øª Ø§Ù„Ù…ÙØªÙˆØ­Ø©',

    settings: 'Ø§Ù„Ø¥Ø¹Ø¯Ø§Ø¯Ø§Øª',
    language: 'Ø§Ù„Ù„ØºØ©',
    arabic: 'Ø§Ù„Ø¹Ø±Ø¨ÙŠØ©',
    english: 'Ø§Ù„Ø¥Ù†Ø¬Ù„ÙŠØ²ÙŠØ©',
    mode: 'Ø§Ù„ÙˆØ¶Ø¹',
    dark: 'Ø¯Ø§ÙƒÙ†',
    light: 'ÙØ§ØªØ­',
    support: 'Ø§Ù„Ø¯Ø¹Ù…',
    supportWhatsapp: 'Ø§Ù„Ø¯Ø¹Ù… / ÙˆØ§ØªØ³Ø§Ø¨',
    supportEmail: 'Ø§Ù„Ø¨Ø±ÙŠØ¯ Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠ',
    logout: 'ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø®Ø±ÙˆØ¬',
    email: 'Ø§Ù„Ø¨Ø±ÙŠØ¯ Ø§Ù„Ø¥Ù„ÙƒØªØ±ÙˆÙ†ÙŠ',
    phone: 'Ø§Ù„Ù‡Ø§ØªÙ',

    openImage: 'ÙØªØ­ Ø§Ù„ØµÙˆØ±Ø©',
    tapCloseToReturn: 'Ø§Ø¶ØºØ· Ø¥ØºÙ„Ø§Ù‚ Ù„Ù„Ø¹ÙˆØ¯Ø©',

    loading: 'Ø¬Ø§Ø±Ù Ø§Ù„ØªØ­Ù…ÙŠÙ„...',
    loadingCustomer: 'Ø¬Ø§Ø±Ù ØªØ­Ù…ÙŠÙ„ Ù…Ø³Ø§Ø­Ø© Ø§Ù„Ø¹Ù…ÙŠÙ„...',
    loadingSupplier: 'Ø¬Ø§Ø±Ù ØªØ­Ù…ÙŠÙ„ Ù…Ø³Ø§Ø­Ø© Ø§Ù„Ù…ÙˆØ±Ø¯...',
    validSupplierPrice: 'Ø£Ø¯Ø®Ù„ Ø³Ø¹Ø±Ø§Ù‹ ØµØ­ÙŠØ­Ø§Ù‹ Ù…Ù† Ø§Ù„Ù…ÙˆØ±Ø¯',
    addAtLeastOneItem: 'Ø£Ø¶Ù Ø¹Ø±Ø¶Ø§Ù‹ ÙˆØ§Ø­Ø¯Ø§Ù‹ Ø¹Ù„Ù‰ Ø§Ù„Ø£Ù‚Ù„ Ù‚Ø¨Ù„ Ø§Ù„Ø¥Ø±Ø³Ø§Ù„.',
    upload4: 'ÙŠÙ…ÙƒÙ†Ùƒ Ø±ÙØ¹ Ø­ØªÙ‰ 4 ØµÙˆØ± Ù„Ù„Ø·Ù„Ø¨.',
    upload5: 'ÙŠÙ…ÙƒÙ†Ùƒ Ø±ÙØ¹ Ø­ØªÙ‰ 5 ØµÙˆØ± Ù„Ù„Ø¹Ø±Ø¶.',
    rejected: 'Ù…Ø±ÙÙˆØ¶',
    accepted: 'Ù…Ù‚Ø¨ÙˆÙ„',
    allVisibleOffers: 'ÙƒÙ„ Ø§Ù„Ø¹Ø±ÙˆØ¶ Ø§Ù„Ø¸Ø§Ù‡Ø±Ø©',
    waitingPickup: 'Ø¨Ø§Ù†ØªØ¸Ø§Ø± Ø§Ù„Ø§Ø³ØªÙ„Ø§Ù…',
    delivering: 'Ù‚ÙŠØ¯ Ø§Ù„ØªÙˆØµÙŠÙ„',
    completed: 'Ù…ÙƒØªÙ…Ù„',
    deliveryCancelled: 'ØªÙ… Ø¥Ù„ØºØ§Ø¡ Ø§Ù„ØªÙˆØµÙŠÙ„. ÙŠØ¬Ø¨ Ù…Ø±Ø§Ø¬Ø¹Ø© Ø§Ù„Ø·Ù„Ø¨ Ù…Ù† Ù‚Ø¨Ù„ Ø§Ù„Ø¥Ø¯Ø§Ø±Ø© Ø£Ùˆ Ø§Ù„Ø¯Ø¹Ù….',
    deliveryWorkflow: 'Ù…Ø³Ø§Ø± Ø§Ù„ØªÙˆØµÙŠÙ„',
    deliveryWorkflowNote: 'ØªØ¹ÙŠÙŠÙ† Ø§Ù„Ø³Ø§Ø¦Ù‚ ÙˆÙˆÙ‚Øª Ø§Ù„Ø§Ø³ØªÙ„Ø§Ù… ÙˆÙ…ÙˆØ¹Ø¯ Ø§Ù„ØªÙˆØµÙŠÙ„ ÙˆØ¥Ø«Ø¨Ø§Øª Ø§Ù„ØªØ³Ù„ÙŠÙ… ØªÙØ¯Ø§Ø± Ù…Ù† Ù‚Ø¨Ù„ Ø§Ù„Ø¥Ø¯Ø§Ø±Ø©.',
    adminDashboard: 'Ø¥Ø¯Ø§Ø±Ø© Ø£ÙˆØªÙˆ Ø¨Ø§Ø±ØªØ³ IQ',
    platformOverview: 'Ù†Ø¸Ø±Ø© Ø¹Ø§Ù…Ø© Ø¹Ù„Ù‰ Ø§Ù„Ù…Ù†ØµØ©',
    loadingDashboard: 'Ø¬Ø§Ø±Ù ØªØ­Ù…ÙŠÙ„ Ù„ÙˆØ­Ø© Ø§Ù„ØªØ­ÙƒÙ…...',
    ordersOnlyAdminAccess: 'ØµÙ„Ø§Ø­ÙŠØ© Ù‡Ø°Ø§ Ø§Ù„Ø­Ø³Ø§Ø¨ Ù„Ø¥Ø¯Ø§Ø±Ø© Ø§Ù„Ø·Ù„Ø¨Ø§Øª ÙÙ‚Ø·.',
    superAdminOnlyUsers: 'Ø¥Ø¯Ø§Ø±Ø© Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù…ÙŠÙ† Ù…ØªØ§Ø­Ø© Ù„Ù„Ø¥Ø¯Ø§Ø±Ø© Ø§Ù„Ø¹Ù„ÙŠØ§ ÙÙ‚Ø·.',
    adminUsers: 'Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù…ÙˆÙ† Ø§Ù„Ø¥Ø¯Ø§Ø±ÙŠÙˆÙ†',
    auditLogs: 'Ø³Ø¬Ù„ Ø§Ù„Ø¹Ù…Ù„ÙŠØ§Øª',
    supplierName: 'Ø§Ø³Ù… Ø§Ù„Ù…ÙˆØ±Ø¯',
    editSupplier: 'ØªØ¹Ø¯ÙŠÙ„ Ø§Ù„Ù…ÙˆØ±Ø¯',
    editSupplierHint: 'ØªØ­Ø¯ÙŠØ« Ø¨ÙŠØ§Ù†Ø§Øª Ø§Ù„Ù…ÙˆØ±Ø¯ ÙˆØ§Ù„Ø£Ù†ÙˆØ§Ø¹ Ø§Ù„Ù…Ø¯Ø¹ÙˆÙ…Ø© ÙˆØ­Ø§Ù„Ø© Ø§Ù„ØªÙØ¹ÙŠÙ„.',
    supplierDetails: 'Ø¨ÙŠØ§Ù†Ø§Øª Ø§Ù„Ù…ÙˆØ±Ø¯',
    supportedMakes: 'Ø§Ù„Ø£Ù†ÙˆØ§Ø¹ Ø§Ù„Ù…Ø¯Ø¹ÙˆÙ…Ø©',
    supportedMakesHint: 'Ø§Ø®ØªØ± Ø§Ù„Ø£Ù†ÙˆØ§Ø¹ Ø§Ù„ØªÙŠ ÙŠÙ…ÙƒÙ† Ù„Ù‡Ø°Ø§ Ø§Ù„Ù…ÙˆØ±Ø¯ Ø®Ø¯Ù…ØªÙ‡Ø§.',
    supplierWillReceiveLeads: 'Ø³ÙŠØ³ØªÙ„Ù… Ø§Ù„Ù…ÙˆØ±Ø¯ Ø§Ù„Ø·Ù„Ø¨Ø§Øª Ø§Ù„Ù…Ø·Ø§Ø¨Ù‚Ø©.',
    supplierWillNotReceiveLeads: 'Ù„Ù† ÙŠØ³ØªÙ„Ù… Ø§Ù„Ù…ÙˆØ±Ø¯ Ø·Ù„Ø¨Ø§Øª Ø¬Ø¯ÙŠØ¯Ø©.',
    location: 'Ø§Ù„Ù…ÙˆÙ‚Ø¹',
    addSupplier: 'Ø¥Ø¶Ø§ÙØ© Ù…ÙˆØ±Ø¯',
    addSupplierHint: 'Ø¥Ù†Ø´Ø§Ø¡ Ù…Ù„Ù Ù…ÙˆØ±Ø¯ ÙˆØ§Ø®ØªÙŠØ§Ø± Ø§Ù„Ø£Ù†ÙˆØ§Ø¹ Ø§Ù„Ù…Ø¯Ø¹ÙˆÙ…Ø©.',
    allOrders: 'ÙƒÙ„ Ø§Ù„Ø·Ù„Ø¨Ø§Øª',
    searchOrderPartSupplier: 'Ø§Ø¨Ø­Ø« Ø¨Ø±Ù‚Ù… Ø§Ù„Ø·Ù„Ø¨ Ø£Ùˆ Ø§Ù„Ù‚Ø·Ø¹Ø© Ø£Ùˆ Ø§Ù„Ù…ÙˆØ±Ø¯',
    allStatuses: 'ÙƒÙ„ Ø§Ù„Ø­Ø§Ù„Ø§Øª',
    allPayments: 'ÙƒÙ„ Ø§Ù„Ù…Ø¯ÙÙˆØ¹Ø§Øª',
    from: 'Ù…Ù†',
    to: 'Ø¥Ù„Ù‰',
    clearFilters: 'Ù…Ø³Ø­ Ø§Ù„ÙÙ„Ø§ØªØ±',
    showing: 'Ø¹Ø±Ø¶',
    of: 'Ù…Ù†',
    noMatchingOrders: 'Ù„Ø§ ØªÙˆØ¬Ø¯ Ø·Ù„Ø¨Ø§Øª Ù…Ø·Ø§Ø¨Ù‚Ø©.',
    customerPhone: 'Ù‡Ø§ØªÙ Ø§Ù„Ø¹Ù…ÙŠÙ„',
    customer: 'Ø§Ù„Ø¹Ù…ÙŠÙ„',
    revenue: 'Ø§Ù„Ø¥ÙŠØ±Ø§Ø¯',
    status: 'Ø§Ù„Ø­Ø§Ù„Ø©',
    cancel: 'Ø¥Ù„ØºØ§Ø¡',
    requests: 'Ø§Ù„Ø·Ù„Ø¨Ø§Øª Ø§Ù„Ø¬Ø¯ÙŠØ¯Ø©',
    platformRevenue: 'Ø¥ÙŠØ±Ø§Ø¯Ø§Øª Ø§Ù„Ù…Ù†ØµØ©',
    pendingPayments: 'Ù…Ø¯ÙÙˆØ¹Ø§Øª Ù‚ÙŠØ¯ Ø§Ù„Ø§Ù†ØªØ¸Ø§Ø±',
    paidOrders: 'Ø·Ù„Ø¨Ø§Øª Ù…Ø¯ÙÙˆØ¹Ø©',
    activeSuppliers: 'Ø§Ù„Ù…ÙˆØ±Ø¯ÙˆÙ† Ø§Ù„Ù†Ø´Ø·ÙˆÙ†',
    supplierEarnings: 'Ø£Ø±Ø¨Ø§Ø­ Ø§Ù„Ù…ÙˆØ±Ø¯ÙŠÙ†',
    noSuppliersYet: 'Ù„Ø§ ÙŠÙˆØ¬Ø¯ Ù…ÙˆØ±Ø¯ÙˆÙ† Ø­Ø§Ù„ÙŠØ§Ù‹.',
    active: 'Ù†Ø´Ø·',
    disabled: 'Ù…Ø¹Ø·Ù„',
    makes: 'Ø§Ù„Ø´Ø±ÙƒØ§Øª / Ø§Ù„Ù…Ù†Ø§Ø´Ø¦',
    none: 'Ù„Ø§ ÙŠÙˆØ¬Ø¯',
    disable: 'ØªØ¹Ø·ÙŠÙ„',
    activeSupplier: 'Ù…ÙˆØ±Ø¯ Ù†Ø´Ø·',
    save: 'Ø­ÙØ¸',
    saving: 'Ø¬Ø§Ø±Ù Ø§Ù„Ø­ÙØ¸...',
    loadingAuditLogs: 'Ø¬Ø§Ø±Ù ØªØ­Ù…ÙŠÙ„ Ø³Ø¬Ù„ Ø§Ù„Ø¹Ù…Ù„ÙŠØ§Øª...',
    noAuditLogsYet: 'Ù„Ø§ ÙŠÙˆØ¬Ø¯ Ø³Ø¬Ù„ Ø¹Ù…Ù„ÙŠØ§Øª Ø­Ø§Ù„ÙŠØ§Ù‹.',
    by: 'Ø¨ÙˆØ§Ø³Ø·Ø©',
    system: 'Ø§Ù„Ù†Ø¸Ø§Ù…',
    paymentControls: 'Ø¥Ø¯Ø§Ø±Ø© Ø§Ù„Ø¯ÙØ¹',
    cashOnDelivery: 'Ø§Ù„Ø¯ÙØ¹ Ø¹Ù†Ø¯ Ø§Ù„Ø§Ø³ØªÙ„Ø§Ù…',
    card: 'Ø¨Ø·Ø§Ù‚Ø©',
    wallet: 'Ù…Ø­ÙØ¸Ø©',
    bankTransfer: 'ØªØ­ÙˆÙŠÙ„ Ø¨Ù†ÙƒÙŠ',
    paid: 'Ù…Ø¯ÙÙˆØ¹',
    failed: 'ÙØ´Ù„ Ø§Ù„Ø¯ÙØ¹',
    refunded: 'Ù…Ø³ØªØ±Ø¬Ø¹',
    updatePayment: 'ØªØ­Ø¯ÙŠØ« Ø§Ù„Ø¯ÙØ¹',
    deliveryAssignment: 'Ø¨ÙŠØ§Ù†Ø§Øª Ø§Ù„ØªÙˆØµÙŠÙ„',
    driverName: 'Ø§Ø³Ù… Ø§Ù„Ø³Ø§Ø¦Ù‚',
    proofOfDeliveryUrl: 'Ø±Ø§Ø¨Ø· Ø¥Ø«Ø¨Ø§Øª Ø§Ù„ØªØ³Ù„ÙŠÙ…',
    proofOfDeliveryImage: 'ØµÙˆØ±Ø© Ø¥Ø«Ø¨Ø§Øª Ø§Ù„ØªØ³Ù„ÙŠÙ…',
    viewProofOfDelivery: 'Ø¹Ø±Ø¶ Ø¥Ø«Ø¨Ø§Øª Ø§Ù„ØªØ³Ù„ÙŠÙ…',
    deliveryNotes: 'Ù…Ù„Ø§Ø­Ø¸Ø§Øª Ø§Ù„ØªÙˆØµÙŠÙ„ / Ù…Ù„Ø§Ø­Ø¸Ø§Øª Ø§Ù„Ø¹Ù…ÙŠÙ„',
    updateDelivery: 'ØªØ­Ø¯ÙŠØ« Ø§Ù„ØªÙˆØµÙŠÙ„',
    createAdminUser: 'Ø¥Ù†Ø´Ø§Ø¡ Ù…Ø³ØªØ®Ø¯Ù… Ø¥Ø¯Ø§Ø±ÙŠ',
    superAdminCreated: 'ØªÙ… Ø¥Ù†Ø´Ø§Ø¡ Ù…Ø³ØªØ®Ø¯Ù… Ø¥Ø¯Ø§Ø±Ø© Ø¹Ù„ÙŠØ§ Ø¨Ù†Ø¬Ø§Ø­.',
    adminCreated: 'ØªÙ… Ø¥Ù†Ø´Ø§Ø¡ Ù…Ø³ØªØ®Ø¯Ù… Ø¥Ø¯Ø§Ø±ÙŠ Ø¨Ù†Ø¬Ø§Ø­.',
    fullAdminDescription: 'Ù…Ø´Ø±Ù ÙƒØ§Ù…Ù„: Ù„ÙˆØ­Ø© Ø§Ù„ØªØ­ÙƒÙ…ØŒ Ø§Ù„Ù…ÙˆØ±Ø¯ÙˆÙ†ØŒ Ø§Ù„Ø·Ù„Ø¨Ø§ØªØŒ Ø³Ø¬Ù„ Ø§Ù„Ø¹Ù…Ù„ÙŠØ§Øª',
    ordersOnlyDescription: 'Ø¥Ø¯Ø§Ø±Ø© Ø§Ù„Ø·Ù„Ø¨Ø§Øª ÙÙ‚Ø·',
    fullName: 'Ø§Ù„Ø§Ø³Ù… Ø§Ù„ÙƒØ§Ù…Ù„',
    phoneNumberForLogin: 'Ø±Ù‚Ù… Ø§Ù„Ù‡Ø§ØªÙ Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù… Ù„Ù„Ø¯Ø®ÙˆÙ„',
    adminPhoneLoginNote: 'ÙŠÙ…ÙƒÙ† Ù„Ù„Ù…Ø´Ø±ÙÙŠÙ† ÙˆØ§Ù„Ø¥Ø¯Ø§Ø±Ø© Ø§Ù„Ø¹Ù„ÙŠØ§ ØªØ³Ø¬ÙŠÙ„ Ø§Ù„Ø¯Ø®ÙˆÙ„ Ù…Ù† Ø´Ø§Ø´Ø© Ø§Ù„Ù‡Ø§ØªÙ Ø§Ù„Ø±Ø¦ÙŠØ³ÙŠØ© Ø¨Ø§Ø³ØªØ®Ø¯Ø§Ù… Ø±Ù‚Ù… Ø§Ù„Ù‡Ø§ØªÙ Ø§Ù„Ù…Ø³Ø¬Ù„. ÙŠØ¨Ù‚Ù‰ Ø²Ø± SA ÙÙŠ Ø§Ù„Ø²Ø§ÙˆÙŠØ© Ù…ØªØ§Ø­Ø§Ù‹ Ù„Ù„Ø¯Ø®ÙˆÙ„ Ø§Ù„Ø·Ø§Ø±Ø¦ Ø¨Ø§Ø³Ù… Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù… ÙˆØ±Ù…Ø² Ø§Ù„ÙˆØµÙˆÙ„ ÙÙ‚Ø·.',
    createUser: 'Ø¥Ù†Ø´Ø§Ø¡ Ø§Ù„Ù…Ø³ØªØ®Ø¯Ù…',
    checkoutPreview: 'Ù…Ø±Ø§Ø¬Ø¹Ø© Ø§Ù„Ø·Ù„Ø¨',
    confirmOrder: 'ØªØ£ÙƒÙŠØ¯ Ø§Ù„Ø·Ù„Ø¨',
    itemPrice: 'Ø³Ø¹Ø± Ø§Ù„Ù‚Ø·Ø¹Ø©',
    deliveryFee: 'Ø±Ø³ÙˆÙ… Ø§Ù„ØªÙˆØµÙŠÙ„',
    total: 'Ø§Ù„Ø¥Ø¬Ù…Ø§Ù„ÙŠ',
    paymentPlaceholder: 'Ø§Ù„Ø¯ÙØ¹ Ø¹Ù†Ø¯ Ø§Ù„Ø§Ø³ØªÙ„Ø§Ù… Ù…ÙØ¹Ù„ Ø­Ø§Ù„ÙŠØ§Ù‹. ÙŠÙ…ÙƒÙ† Ø±Ø¨Ø· Ø§Ù„Ø¯ÙØ¹ Ø¨Ø§Ù„Ø¨Ø·Ø§Ù‚Ø© Ø£Ùˆ Ø§Ù„Ù…Ø­ÙØ¸Ø© Ù„Ø§Ø­Ù‚Ø§Ù‹.',
    confirming: 'Ø¬Ø§Ø±Ù Ø§Ù„ØªØ£ÙƒÙŠØ¯...',
    notAvailable: 'ØºÙŠØ± Ù…ØªÙˆÙØ±',
    origin: 'Ø§Ù„Ù…Ù†Ø´Ø£',
    make: 'Ø§Ù„Ø´Ø±ÙƒØ© Ø§Ù„Ù…ØµÙ†Ø¹Ø©',
    model: 'Ø§Ù„Ù…ÙˆØ¯ÙŠÙ„',
    year: 'Ø§Ù„Ø³Ù†Ø©',
    activeOffer: 'Ù†Ø´Ø·',
    waiting: 'Ù‚ÙŠØ¯ Ø§Ù„Ø§Ù†ØªØ¸Ø§Ø±',
    processing: 'Ù‚ÙŠØ¯ Ø§Ù„Ù…Ø¹Ø§Ù„Ø¬Ø©',
    newOfferNotification: 'Ù„Ø¯ÙŠÙƒ Ø¹Ø±Ø¶ Ø¬Ø¯ÙŠØ¯',
    offerAcceptedNotification: 'ØªÙ… Ù‚Ø¨ÙˆÙ„ Ø¹Ø±Ø¶Ùƒ',
    orderStatusUpdatedNotification: 'ØªÙ… ØªØ­Ø¯ÙŠØ« Ø­Ø§Ù„Ø© Ø§Ù„Ø·Ù„Ø¨',
    orderPaymentUpdatedNotification: 'ØªÙ… ØªØ­Ø¯ÙŠØ« Ø§Ù„Ø¯ÙØ¹',
    orderDeliveryUpdatedNotification: 'ØªÙ… ØªØ­Ø¯ÙŠØ« Ø¨ÙŠØ§Ù†Ø§Øª Ø§Ù„ØªÙˆØµÙŠÙ„',
    proofOfDeliveryUpdatedNotification: 'ØªÙ… ØªØ­Ø¯ÙŠØ« Ø¥Ø«Ø¨Ø§Øª Ø§Ù„ØªØ³Ù„ÙŠÙ…',
    created: 'ØªØ§Ø±ÙŠØ® Ø§Ù„Ø¥Ù†Ø´Ø§Ø¡',
    noOrders: 'Ù„Ø§ ØªÙˆØ¬Ø¯ Ø·Ù„Ø¨Ø§Øª Ø­Ø§Ù„ÙŠØ§Ù‹.',
    user: 'Ù…Ø³ØªØ®Ø¯Ù…',
    order: 'Ø·Ù„Ø¨',
    auditAdminUserCreated: 'ØªÙ… Ø¥Ù†Ø´Ø§Ø¡ Ù…Ø³ØªØ®Ø¯Ù… Ø¥Ø¯Ø§Ø±ÙŠ',
    auditOrderStatusUpdated: 'ØªÙ… ØªØ­Ø¯ÙŠØ« Ø­Ø§Ù„Ø© Ø§Ù„Ø·Ù„Ø¨',
    auditSupplierCreated: 'ØªÙ… Ø¥Ù†Ø´Ø§Ø¡ Ù…ÙˆØ±Ø¯',
    auditSupplierUpdated: 'ØªÙ… ØªØ­Ø¯ÙŠØ« Ù…ÙˆØ±Ø¯',
    auditSupplierDisabled: 'ØªÙ… ØªØ¹Ø·ÙŠÙ„ Ù…ÙˆØ±Ø¯',
    auditPaymentUpdated: 'ØªÙ… ØªØ­Ø¯ÙŠØ« Ø§Ù„Ø¯ÙØ¹',
    auditDeliveryUpdated: 'ØªÙ… ØªØ­Ø¯ÙŠØ« Ø§Ù„ØªÙˆØµÙŠÙ„'
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(localStorage.getItem('language') || 'en');
  const value = useMemo(() => ({
    language,
    direction: language === 'ar' ? 'rtl' : 'ltr',
    t: key => translations[language][key] || translations.en[key] || key,
    toggleLanguage: () => {
      const next = language === 'en' ? 'ar' : 'en';
      localStorage.setItem('language', next);
      setLanguage(next);
    }
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export const useLanguage = () => useContext(LanguageContext);
