import React, { createContext, useContext, useMemo, useState } from 'react';

const translations = {
  en: {
    appName: 'AutoParts IQ',
    iraqiPartsMarket: 'Iraqi spare parts marketplace',
    landingSubtitle: 'Find parts faster, receive supplier offers, and track orders from one place.',
    enterLogin: 'Enter / Log In',
    phoneLogin: 'Phone number login',
    enterPhone: 'Enter your phone number',
    phoneNumber: 'Phone number',
    continue: 'Continue',
    back: 'Back',
    enterOtp: 'Enter OTP',
    verifySignIn: 'Verify & Sign In',
    changeNumber: 'Change number',

    adminAccess: 'Admin Access',
    usernameEmailPhone: 'Username, email, or phone',
    password: 'Password',
    signIn: 'Sign in',
    signingIn: 'Signing in...',
    backToPhoneLogin: 'Back to phone login',

    roleCustomer: 'CUSTOMER',
    roleSupplier: 'SUPPLIER',
    roleAdmin: 'ADMIN',
    roleSuperAdmin: 'SUPER ADMIN',

    home: 'Home',
    orders: 'Orders',
    profile: 'Profile',
    leads: 'Leads',
    sentOffers: 'Sent Offers',
    activeOffers: 'Active Offers',
    requestDetails: 'Request Details',
    offerDetails: 'Offer Details',
    earnings: 'Earnings',
    suppliers: 'Suppliers',
    dashboard: 'Dashboard',
    audit: 'Audit',
    users: 'Users',
    notifications: 'Notifications',
    close: 'Close',
    noNotifications: 'No notifications yet.',
    tapToOpen: 'Tap to open',

    hello: 'Hello',
    findParts: 'Find car parts faster',
    newRequest: '+ New Request',
    myRequests: 'My Requests',
    openRequests: 'Open Requests',
    submitRequest: 'Submit Request',
    requestSubmitted: 'Your request was submitted successfully.',
    noMatchingRequests: 'No matching requests.',
    pending: 'Pending',
    cancelled: 'Cancelled',
    pendingCancelled: 'Pending + Cancelled',
    details: 'Details',
    partDetails: 'Part / Request',
    hide: 'Hide',
    cancelRequest: 'Cancel request',
    reasonForCancellation: 'Reason for cancellation',
    confirmCancel: 'Confirm cancel',
    keepRequest: 'Keep request',
    requestCancelled: 'Request cancelled successfully.',

    selectOrigin: 'Select origin',
    selectMake: 'Select make',
    selectModel: 'Select model',
    selectYear: 'Select year',
    describeProblem: 'Describe problem e.g. squeaking brakes',
    aiIdentify: 'AI Identify Part',
    analyzing: 'Analyzing...',
    partName: 'Part name',
    partNumber: 'Part number',
    vinChassis: 'VIN / chassis',
    description: 'Description',
    requestPhotosUpTo4: 'Request photos — up to 4',
    uploadPhoto: 'Upload photo',
    uploading: 'Uploading...',
    imageHelp: 'JPG, PNG, WEBP, or GIF. Max 5MB per image.',
    yourPhone: 'Your phone',
    detailedLocation: 'Detailed location',

    supplier: 'Supplier',
    price: 'Price',
    priceBreakdown: 'Price Breakdown',
    condition: 'Condition',
    delivery: 'Delivery',
    new: 'New',
    used: 'Used',
    checkout: 'Checkout',
    offerAccepted: 'Offer accepted successfully. Your order has been created.',
    payment: 'Payment',
    paymentStatus: 'Payment status',
    driver: 'Driver',
    driverPhone: 'Driver phone',
    pickupEta: 'Pickup ETA',
    deliveryEta: 'Delivery ETA',
    deliveryComments: 'Delivery comments',
    notAssigned: 'Not assigned',

    supplierWorkspace: 'Supplier workspace',
    offersLeads: 'Offers & Leads',
    noMatchingLeads: 'No matching leads yet.',
    noMatchingSentOffers: 'No matching sent offers.',
    noAcceptedOrders: 'No accepted orders yet.',
    open: 'Open',
    addOfferItem: 'Add offer item',
    netPriceIqd: 'Net price IQD',
    notes: 'Notes',
    uploadOfferPhoto: 'Upload offer photo',
    addItem: 'Add Item',
    updateItem: 'Update Item',
    clear: 'Clear',
    itemsReady: 'Items ready to submit',
    submitOfferItems: 'Submit Offer Items',
    offerItemsSubmitted: 'Offer items submitted successfully.',
    edit: 'Edit',
    remove: 'Remove',
    cancelSentOffer: 'Cancel sent offer',
    confirmCancellation: 'Confirm cancellation',
    offerCancelled: 'Offer cancelled successfully.',
    yourPrice: 'Your price',
    completedEarningsOnly: 'Completed earnings only',
    pendingValue: 'Pending Value',
    pendingValueNote: 'Pending value is not final until the order is completed.',
    openOrders: 'Open Orders',
    openTransactions: 'Open Transactions',
    noPendingValue: 'No pending value transactions.',
    completedOrders: 'Completed Orders',
    pendingOrders: 'Pending Orders',
    completedTransactions: 'Completed Transactions',
    noCompletedEarnings: 'No completed earnings transactions yet.',
    orderReadOnly: 'Order status is managed by Admin. Supplier view is read-only.',
    activeOrders: 'Open Orders',

    settings: 'Settings',
    language: 'Language',
    arabic: 'Arabic',
    english: 'English',
    mode: 'Mode',
    dark: 'Dark',
    light: 'Light',
    support: 'Support',
    supportWhatsapp: 'Support / WhatsApp',
    supportEmail: 'Support Email',
    logout: 'Log out',
    email: 'Email',
    phone: 'Phone',

    openImage: 'Open image',
    tapCloseToReturn: 'Tap Close to return',

    loading: 'Loading...',
    loadingCustomer: 'Loading customer workspace...',
    loadingSupplier: 'Loading supplier workspace...',
    validSupplierPrice: 'Valid supplier price is needed',
    addAtLeastOneItem: 'Add at least one item before submitting.',
    upload4: 'You can upload up to 4 request photos.',
    upload5: 'You can upload up to 5 offer photos.',
    rejected: 'Rejected',
    accepted: 'Accepted',
    allVisibleOffers: 'All visible offers',
    waitingPickup: 'Waiting pickup',
    delivering: 'Delivering',
    completed: 'Completed',
    deliveryCancelled: 'Delivery cancelled. Admin or support should review this order.',
    deliveryWorkflow: 'Delivery workflow',
    deliveryWorkflowNote: 'Driver assignment, pickup time, delivery ETA, and proof of delivery are managed by Admin.',
    adminDashboard: 'AutoPartIQ Admin',
    platformOverview: 'Platform overview',
    loadingDashboard: 'Loading dashboard...',
    ordersOnlyAdminAccess: 'Orders-only admin access.',
    superAdminOnlyUsers: 'Only Super Admin can manage admin users.',
    adminUsers: 'Admin Users',
    auditLogs: 'Audit Logs',
    supplierName: 'Supplier name',
    editSupplier: 'Edit Supplier',
    editSupplierHint: 'Update supplier details, supported origins, and active status.',
    supplierDetails: 'Supplier Details',
    supportedMakes: 'Supported Makes',
    supportedMakesHint: 'Choose the origins this supplier can serve.',
    supplierWillReceiveLeads: 'Supplier will receive matching leads.',
    supplierWillNotReceiveLeads: 'Supplier will not receive new leads.',
    location: 'Location',
    addSupplier: 'Add Supplier',
    addSupplierHint: 'Create a supplier profile and choose supported origins.',
    allOrders: 'All Orders',
    searchOrderPartSupplier: 'Search order, part, or supplier',
    allStatuses: 'All statuses',
    from: 'From',
    to: 'To',
    clearFilters: 'Clear filters',
    showing: 'Showing',
    of: 'of',
    noMatchingOrders: 'No matching orders.',
    customerPhone: 'Customer phone',
    customer: 'Customer',
    revenue: 'Revenue',
    status: 'Status',
    cancel: 'Cancel',
    requests: 'Requests',
    platformRevenue: 'Platform Revenue',
    pendingPayments: 'Pending Payments',
    paidOrders: 'Paid Orders',
    activeSuppliers: 'Active Suppliers',
    supplierEarnings: 'Supplier Earnings',
    noSuppliersYet: 'No suppliers yet.',
    active: 'Active',
    disabled: 'Disabled',
    makes: 'Makes',
    none: 'None',
    disable: 'Disable',
    activeSupplier: 'Active supplier',
    save: 'Save',
    saving: 'Saving...',
    loadingAuditLogs: 'Loading audit logs...',
    noAuditLogsYet: 'No audit logs yet.',
    by: 'By',
    system: 'System',
    paymentControls: 'Payment controls',
    cashOnDelivery: 'Cash on delivery',
    card: 'Card',
    wallet: 'Wallet',
    bankTransfer: 'Bank transfer',
    paid: 'Paid',
    failed: 'Failed',
    refunded: 'Refunded',
    updatePayment: 'Update payment',
    deliveryAssignment: 'Delivery assignment',
    driverName: 'Driver name',
    proofOfDeliveryUrl: 'Proof of delivery URL',
    proofOfDeliveryImage: 'Proof of delivery image',
    viewProofOfDelivery: 'View proof of delivery',
    deliveryNotes: 'Delivery notes / customer comments',
    updateDelivery: 'Update delivery',
    createAdminUser: 'Create Admin User',
    superAdminCreated: 'Super Admin created successfully.',
    adminCreated: 'Admin created successfully.',
    fullAdminDescription: 'Full Admin: dashboard, suppliers, orders, audit',
    ordersOnlyDescription: 'Orders Only: order management only',
    fullName: 'Full name',
    phoneNumberForLogin: 'Phone number used for login',
    adminPhoneLoginNote: 'Admin and Super Admin users can log in from the main phone login screen using their registered phone number. The corner SA button remains available for emergency username/access-code access only.',
    createUser: 'Create User',
    checkoutPreview: 'Checkout preview',
    confirmOrder: 'Confirm order',
    itemPrice: 'Item price',
    deliveryFee: 'Delivery fee',
    total: 'Total',
    paymentPlaceholder: 'Cash on delivery is active for MVP. Card and wallet payment can be connected later.',
    confirming: 'Confirming...',
    notAvailable: 'N/A',
    origin: 'Origin',
    make: 'Make',
    model: 'Model',
    year: 'Year',
    activeOffer: 'Active',
    waiting: 'Waiting',
    processing: 'Processing',
    newOfferNotification: 'You have a new offer',
    offerAcceptedNotification: 'Your offer was accepted',
    orderStatusUpdatedNotification: 'Order status updated',
    orderPaymentUpdatedNotification: 'Payment updated',
    orderDeliveryUpdatedNotification: 'Delivery details updated',
    proofOfDeliveryUpdatedNotification: 'Proof of delivery updated',
    created: 'Created',
    noOrders: 'No orders yet.',
    user: 'User',
    order: 'Order',
    auditAdminUserCreated: 'Admin user created',
    auditOrderStatusUpdated: 'Order status updated',
    auditSupplierCreated: 'Supplier created',
    auditSupplierUpdated: 'Supplier updated',
    auditSupplierDisabled: 'Supplier disabled',
    auditPaymentUpdated: 'Payment updated',
    auditDeliveryUpdated: 'Delivery updated'
  },

  ar: {
    appName: 'أوتو بارتس IQ',
    iraqiPartsMarket: 'سوق قطع الغيار العراقي',
    landingSubtitle: 'ابحث عن قطع الغيار بسرعة، استلم عروض الموردين، وتابع طلباتك من مكان واحد.',
    enterLogin: 'دخول',
    phoneLogin: 'تسجيل الدخول برقم الهاتف',
    enterPhone: 'أدخل رقم الهاتف',
    phoneNumber: 'رقم الهاتف',
    continue: 'متابعة',
    back: 'رجوع',
    enterOtp: 'أدخل رمز التحقق',
    verifySignIn: 'تحقق وتسجيل الدخول',
    changeNumber: 'تغيير الرقم',

    adminAccess: 'دخول الإدارة',
    usernameEmailPhone: 'اسم المستخدم أو البريد أو رقم الهاتف',
    password: 'كلمة المرور',
    signIn: 'تسجيل الدخول',
    signingIn: 'جارٍ تسجيل الدخول...',
    backToPhoneLogin: 'الرجوع لتسجيل الدخول بالهاتف',

    roleCustomer: 'عميل',
    roleSupplier: 'مورد',
    roleAdmin: 'مشرف',
    roleSuperAdmin: 'إدارة عليا',

    home: 'الرئيسية',
    orders: 'الطلبات',
    profile: 'الملف الشخصي',
    leads: 'الطلبات الجديدة',
    sentOffers: 'العروض المرسلة',
    activeOffers: 'العروض النشطة',
    requestDetails: 'تفاصيل الطلب',
    offerDetails: 'تفاصيل العرض',
    earnings: 'الأرباح',
    suppliers: 'الموردون',
    dashboard: 'لوحة التحكم',
    audit: 'سجل العمليات',
    users: 'المستخدمون',
    notifications: 'الإشعارات',
    close: 'إغلاق',
    noNotifications: 'لا توجد إشعارات حالياً.',
    tapToOpen: 'اضغط للفتح',

    hello: 'مرحباً',
    findParts: 'اعثر على قطع غيار سيارتك بسرعة',
    newRequest: '+ طلب جديد',
    myRequests: 'طلباتي',
    openRequests: 'الطلبات المفتوحة',
    submitRequest: 'إرسال الطلب',
    requestSubmitted: 'تم إرسال طلبك بنجاح.',
    noMatchingRequests: 'لا توجد طلبات مطابقة.',
    pending: 'قيد الانتظار',
    cancelled: 'ملغي',
    pendingCancelled: 'قيد الانتظار + ملغي',
    details: 'التفاصيل',
    partDetails: 'تفاصيل القطعة / الطلب',
    hide: 'إخفاء',
    cancelRequest: 'إلغاء الطلب',
    reasonForCancellation: 'سبب الإلغاء',
    confirmCancel: 'تأكيد الإلغاء',
    keepRequest: 'الإبقاء على الطلب',
    requestCancelled: 'تم إلغاء الطلب بنجاح.',

    selectOrigin: 'اختر المنشأ',
    selectMake: 'اختر الشركة المصنعة',
    selectModel: 'اختر الموديل',
    selectYear: 'اختر السنة',
    describeProblem: 'صف المشكلة، مثال: صوت في الفرامل',
    aiIdentify: 'تحديد القطعة بالذكاء الاصطناعي',
    analyzing: 'جارٍ التحليل...',
    partName: 'اسم القطعة',
    partNumber: 'رقم القطعة',
    vinChassis: 'رقم الشاصي / VIN',
    description: 'الوصف',
    requestPhotosUpTo4: 'صور الطلب — حتى 4 صور',
    uploadPhoto: 'رفع صورة',
    uploading: 'جارٍ الرفع...',
    imageHelp: 'الصيغ المسموحة JPG أو PNG أو WEBP أو GIF. الحد الأقصى 5MB للصورة.',
    yourPhone: 'رقم هاتفك',
    detailedLocation: 'الموقع التفصيلي',

    supplier: 'المورد',
    price: 'السعر',
    priceBreakdown: 'تفاصيل السعر',
    condition: 'الحالة',
    delivery: 'التوصيل',
    new: 'جديد',
    used: 'مستعمل',
    checkout: 'تأكيد الطلب',
    offerAccepted: 'تم قبول العرض بنجاح وتم إنشاء الطلب.',
    payment: 'طريقة الدفع',
    paymentStatus: 'حالة الدفع',
    driver: 'السائق',
    driverPhone: 'هاتف السائق',
    pickupEta: 'موعد الاستلام المتوقع',
    deliveryEta: 'موعد التوصيل المتوقع',
    deliveryComments: 'ملاحظات التوصيل',
    notAssigned: 'لم يتم التعيين',

    supplierWorkspace: 'مساحة المورد',
    offersLeads: 'العروض والطلبات الجديدة',
    noMatchingLeads: 'لا توجد طلبات جديدة مطابقة حالياً.',
    noMatchingSentOffers: 'لا توجد عروض مرسلة مطابقة.',
    noAcceptedOrders: 'لا توجد طلبات مقبولة حالياً.',
    open: 'فتح',
    addOfferItem: 'إضافة عرض',
    netPriceIqd: 'السعر الصافي بالدينار',
    notes: 'ملاحظات',
    uploadOfferPhoto: 'رفع صورة العرض',
    addItem: 'إضافة',
    updateItem: 'تحديث',
    clear: 'مسح',
    itemsReady: 'عروض جاهزة للإرسال',
    submitOfferItems: 'إرسال العروض',
    offerItemsSubmitted: 'تم إرسال العروض بنجاح.',
    edit: 'تعديل',
    remove: 'حذف',
    cancelSentOffer: 'إلغاء العرض المرسل',
    confirmCancellation: 'تأكيد الإلغاء',
    offerCancelled: 'تم إلغاء العرض بنجاح.',
    yourPrice: 'سعرك',
    completedEarningsOnly: 'الأرباح من الطلبات المكتملة فقط',
    pendingValue: 'القيمة المعلقة',
    pendingValueNote: 'القيمة المعلقة ليست نهائية حتى اكتمال الطلب.',
    openOrders: 'الطلبات المفتوحة',
    openTransactions: 'العمليات المفتوحة',
    noPendingValue: 'لا توجد قيم معلقة حالياً.',
    completedOrders: 'الطلبات المكتملة',
    pendingOrders: 'الطلبات قيد التنفيذ',
    completedTransactions: 'العمليات المكتملة',
    noCompletedEarnings: 'لا توجد أرباح مكتملة حالياً.',
    orderReadOnly: 'حالة الطلب تُدار من قبل الإدارة. عرض المورد للقراءة فقط.',
    activeOrders: 'الطلبات المفتوحة',

    settings: 'الإعدادات',
    language: 'اللغة',
    arabic: 'العربية',
    english: 'الإنجليزية',
    mode: 'الوضع',
    dark: 'داكن',
    light: 'فاتح',
    support: 'الدعم',
    supportWhatsapp: 'الدعم / واتساب',
    supportEmail: 'البريد الإلكتروني',
    logout: 'تسجيل الخروج',
    email: 'البريد الإلكتروني',
    phone: 'الهاتف',

    openImage: 'فتح الصورة',
    tapCloseToReturn: 'اضغط إغلاق للعودة',

    loading: 'جارٍ التحميل...',
    loadingCustomer: 'جارٍ تحميل مساحة العميل...',
    loadingSupplier: 'جارٍ تحميل مساحة المورد...',
    validSupplierPrice: 'أدخل سعراً صحيحاً من المورد',
    addAtLeastOneItem: 'أضف عرضاً واحداً على الأقل قبل الإرسال.',
    upload4: 'يمكنك رفع حتى 4 صور للطلب.',
    upload5: 'يمكنك رفع حتى 5 صور للعرض.',
    rejected: 'مرفوض',
    accepted: 'مقبول',
    allVisibleOffers: 'كل العروض الظاهرة',
    waitingPickup: 'بانتظار الاستلام',
    delivering: 'قيد التوصيل',
    completed: 'مكتمل',
    deliveryCancelled: 'تم إلغاء التوصيل. يجب مراجعة الطلب من قبل الإدارة أو الدعم.',
    deliveryWorkflow: 'مسار التوصيل',
    deliveryWorkflowNote: 'تعيين السائق ووقت الاستلام وموعد التوصيل وإثبات التسليم تُدار من قبل الإدارة.',
    adminDashboard: 'إدارة أوتو بارتس IQ',
    platformOverview: 'نظرة عامة على المنصة',
    loadingDashboard: 'جارٍ تحميل لوحة التحكم...',
    ordersOnlyAdminAccess: 'صلاحية هذا الحساب لإدارة الطلبات فقط.',
    superAdminOnlyUsers: 'إدارة المستخدمين متاحة للإدارة العليا فقط.',
    adminUsers: 'المستخدمون الإداريون',
    auditLogs: 'سجل العمليات',
    supplierName: 'اسم المورد',
    editSupplier: 'تعديل المورد',
    editSupplierHint: 'تحديث بيانات المورد والأنواع المدعومة وحالة التفعيل.',
    supplierDetails: 'بيانات المورد',
    supportedMakes: 'الأنواع المدعومة',
    supportedMakesHint: 'اختر الأنواع التي يمكن لهذا المورد خدمتها.',
    supplierWillReceiveLeads: 'سيستلم المورد الطلبات المطابقة.',
    supplierWillNotReceiveLeads: 'لن يستلم المورد طلبات جديدة.',
    location: 'الموقع',
    addSupplier: 'إضافة مورد',
    addSupplierHint: 'إنشاء ملف مورد واختيار الأنواع المدعومة.',
    allOrders: 'كل الطلبات',
    searchOrderPartSupplier: 'ابحث برقم الطلب أو القطعة أو المورد',
    allStatuses: 'كل الحالات',
    allPayments: 'كل المدفوعات',
    from: 'من',
    to: 'إلى',
    clearFilters: 'مسح الفلاتر',
    showing: 'عرض',
    of: 'من',
    noMatchingOrders: 'لا توجد طلبات مطابقة.',
    customerPhone: 'هاتف العميل',
    customer: 'العميل',
    revenue: 'الإيراد',
    status: 'الحالة',
    cancel: 'إلغاء',
    requests: 'الطلبات الجديدة',
    platformRevenue: 'إيرادات المنصة',
    pendingPayments: 'مدفوعات قيد الانتظار',
    paidOrders: 'طلبات مدفوعة',
    activeSuppliers: 'الموردون النشطون',
    supplierEarnings: 'أرباح الموردين',
    noSuppliersYet: 'لا يوجد موردون حالياً.',
    active: 'نشط',
    disabled: 'معطل',
    makes: 'الشركات / المناشئ',
    none: 'لا يوجد',
    disable: 'تعطيل',
    activeSupplier: 'مورد نشط',
    save: 'حفظ',
    saving: 'جارٍ الحفظ...',
    loadingAuditLogs: 'جارٍ تحميل سجل العمليات...',
    noAuditLogsYet: 'لا يوجد سجل عمليات حالياً.',
    by: 'بواسطة',
    system: 'النظام',
    paymentControls: 'إدارة الدفع',
    cashOnDelivery: 'الدفع عند الاستلام',
    card: 'بطاقة',
    wallet: 'محفظة',
    bankTransfer: 'تحويل بنكي',
    paid: 'مدفوع',
    failed: 'فشل الدفع',
    refunded: 'مسترجع',
    updatePayment: 'تحديث الدفع',
    deliveryAssignment: 'بيانات التوصيل',
    driverName: 'اسم السائق',
    proofOfDeliveryUrl: 'رابط إثبات التسليم',
    proofOfDeliveryImage: 'صورة إثبات التسليم',
    viewProofOfDelivery: 'عرض إثبات التسليم',
    deliveryNotes: 'ملاحظات التوصيل / ملاحظات العميل',
    updateDelivery: 'تحديث التوصيل',
    createAdminUser: 'إنشاء مستخدم إداري',
    superAdminCreated: 'تم إنشاء مستخدم إدارة عليا بنجاح.',
    adminCreated: 'تم إنشاء مستخدم إداري بنجاح.',
    fullAdminDescription: 'مشرف كامل: لوحة التحكم، الموردون، الطلبات، سجل العمليات',
    ordersOnlyDescription: 'إدارة الطلبات فقط',
    fullName: 'الاسم الكامل',
    phoneNumberForLogin: 'رقم الهاتف المستخدم للدخول',
    adminPhoneLoginNote: 'يمكن للمشرفين والإدارة العليا تسجيل الدخول من شاشة الهاتف الرئيسية باستخدام رقم الهاتف المسجل. يبقى زر SA في الزاوية متاحاً للدخول الطارئ باسم المستخدم ورمز الوصول فقط.',
    createUser: 'إنشاء المستخدم',
    checkoutPreview: 'مراجعة الطلب',
    confirmOrder: 'تأكيد الطلب',
    itemPrice: 'سعر القطعة',
    deliveryFee: 'رسوم التوصيل',
    total: 'الإجمالي',
    paymentPlaceholder: 'الدفع عند الاستلام مفعل حالياً. يمكن ربط الدفع بالبطاقة أو المحفظة لاحقاً.',
    confirming: 'جارٍ التأكيد...',
    notAvailable: 'غير متوفر',
    origin: 'المنشأ',
    make: 'الشركة المصنعة',
    model: 'الموديل',
    year: 'السنة',
    activeOffer: 'نشط',
    waiting: 'قيد الانتظار',
    processing: 'قيد المعالجة',
    newOfferNotification: 'لديك عرض جديد',
    offerAcceptedNotification: 'تم قبول عرضك',
    orderStatusUpdatedNotification: 'تم تحديث حالة الطلب',
    orderPaymentUpdatedNotification: 'تم تحديث الدفع',
    orderDeliveryUpdatedNotification: 'تم تحديث بيانات التوصيل',
    proofOfDeliveryUpdatedNotification: 'تم تحديث إثبات التسليم',
    created: 'تاريخ الإنشاء',
    noOrders: 'لا توجد طلبات حالياً.',
    user: 'مستخدم',
    order: 'طلب',
    auditAdminUserCreated: 'تم إنشاء مستخدم إداري',
    auditOrderStatusUpdated: 'تم تحديث حالة الطلب',
    auditSupplierCreated: 'تم إنشاء مورد',
    auditSupplierUpdated: 'تم تحديث مورد',
    auditSupplierDisabled: 'تم تعطيل مورد',
    auditPaymentUpdated: 'تم تحديث الدفع',
    auditDeliveryUpdated: 'تم تحديث التوصيل'
  }
};

const LanguageContext = createContext(null);

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(localStorage.getItem('language') || 'en');
  const value = useMemo(() => ({
    language,
    direction: language === 'ar' ? 'rtl' : 'ltr',
    t: key => translations[language][key] || translations.en[key] || key,
    toggleLanguage: () => {
      const next = language === 'en' ? 'ar' : 'en';
      localStorage.setItem('language', next);
      setLanguage(next);
    }
  }), [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export const useLanguage = () => useContext(LanguageContext);
